### ISSUE TITLE
add makeFunction?

### ISSUE THREAD

**Issue by giuseppec** [jakobbossek/smoof#50] opened 2015-11-05 11:34 UTC
Suggestion:
add a `makeFunction(fun.name, dimension, ...)` Function

Why?
I would like to do something like

```r
lapply(as.list(filterFunctionsByTags(tags = c("multimodal", "continuous", "scalable"))),
  function(x) makeFunction(fun.name = x))
```

Currently I have to first lookup the function names with `filterFunctionsByTags(tags = c("multimodal", "continuous", "scalable"))` and then search for the respective `make***Function` to create the function. Or is there another possibility to use the resuls of `filterFunctionsByTags` to set multiple functions?

**Comment by jakobbossek** [comment] 2015-11-05 11:59
Already had that function in mind. Working on it now.
A problem we might discuss here: imagine some of the functions you filtered do expect a `dimension` attribute and others not. How to take that into consideration?
1. Simply throw an error if dimension is passed to `makeFunction`, e.g. `(fun.name = x, dimension = 2L)`, but no dimension is expected.
2. Ignore the passed `dimension` and just generate the function. In this case we want to output a warning for sure.

I prefer the first one. In this context we maybe should add some helper functions like `isScalable` so we could do the following.

```splus
lapply(as.list(filterFunctionsByTags(tags = c("multimodal", "scalable"))), function(x) {
  if (isScalable(x)) {
    return(makeFunction(x, dimensions = 2L))
  }
  return(makeFunction(x))
})
```

**Comment by giuseppec** [comment] 2015-11-05 12:05
I guess all functions without the `dimension` arg are 2d functions, right?
If yes, then I think that for `makeFunction(fun.name = x, dimension = 2L)`, it is okay if we just ignore the passed `dimension` because the function exist in 2d. However, for `makeFunction(fun.name = x, dimension = 3L)` an error should be produced that tells us that the function does not exist for the given dimension. What do you think?

**Comment by jakobbossek** [comment] 2015-11-05 12:06
:+1: Completely agree. That was what I meant.
However, I think this `isScalable` or in general `hasTag` function might be helpful as well.

**Comment by jakobbossek** [comment] 2015-11-05 13:29
Done. The example code from your initial posting here should work now.
Close this if you are happy with the new function.

**Comment by giuseppec** [comment] 2015-11-05 13:53
Little bug?

```r
tags = getAvailableTags()
allFuns = unique(unlist(lapply(as.list(tags), filterFunctionsByTags)))

for (i in allFuns) {
  err <- try(makeFunctionByName(fun.name=i, dimensions = 2), silent = TRUE)
  if (is.error(err)) cat(i, fill = TRUE) 
}

```
At least `Alpine01` and `Rosenbrock` should not produce an error when creating them with `dimensions=2`. Maybe you can write a unit test with this code.

**Comment by jakobbossek** [comment] 2015-11-05 15:51
No, not a bug in `makeFunctionByName`. The *scalable* tag is missing for these functions. Added it. Going to push as soon as I arrive at home.

**Comment by jakobbossek** [comment] 2015-11-05 23:18
Done.

**Closed by jakobbossek** 2015-11-05 23:18 UTC
Labels: enhancement
